# {{projectName}}

Generated by `create-qa-app`.

## Stack
- Framework: {{frameworkLabel}}
- Architecture: {{architectureLabel}}
- Language: TypeScript
- Runtime validation: Zod
- Reporting: Allure

## Getting Started
1. Install dependencies with your package manager.
2. Run type checks with `npm run typecheck`.
3. Run your test suite.

## Scripts
- `npm run test` to run tests
- `npm run test:open` to open Cypress app
- `npm run report:allure` to open Allure report

## Architecture Notes
- `pom` keeps page abstractions separate from tests for long-term maintainability.
- `feature` keeps test assets grouped by business feature for easier ownership.
