# {{projectName}}

Generated by `create-qa-app`.

## Stack
- Framework: {{frameworkLabel}}
- Architecture: {{architectureLabel}}
- Language: TypeScript
- Runtime validation: Zod
- Reporting: Allure

## Getting Started
1. Install dependencies with `{{installCommand}}`.
2. Run type checks with `{{typecheckCommand}}`.
3. Run your test suite.

## Scripts
- `{{testCommand}}` to run tests
- `{{openCommand}}` to open Cypress app
- `{{allureReportCommand}}` to open Allure report

## Architecture Notes
- `pom` keeps page abstractions separate from tests for long-term maintainability.
- `feature` keeps test assets grouped by business feature for easier ownership.
