import { afterEach, describe, expect, test } from "bun:test";
import { access, stat } from "node:fs/promises";
import path from "node:path";
import { constants } from "node:fs";
import { scaffoldProject } from "../cli/src/core/scaffold";
import {
  createAdvancedPlaywrightConfig,
  createPlaywrightConfig
} from "./helpers/playwright-config.fixture";
import { createTempDir, readTextFiles, removeTempDir, writeTextFile } from "./helpers/fs";
import { resolvedVersions } from "./helpers/resolved-versions";

const tempDirs: string[] = [];

afterEach(async () => {
  while (tempDirs.length > 0) {
    const tempDir = tempDirs.pop();

    if (tempDir) {
      await removeTempDir(tempDir);
    }
  }
});

describe("scaffold project", () => {
  test("scaffolds a minimal Playwright project with rendered files", async () => {
    const baseDir = await createTempDir("scaffold-minimal-");
    tempDirs.push(baseDir);

    const result = await scaffoldProject(baseDir, createPlaywrightConfig(), {
      resolvedVersions
    });

    const files = await readTextFiles(result.targetDir);

    expect(result.createdFiles).toBeGreaterThan(0);
    expect(result.targetDir).toBe(path.join(baseDir, "my-qa-app"));
    expect(files["README.md"]).toContain("Generated by `create-qa-app`.");
    expect(files["package.json"]).toContain('"@playwright/test": "1.58.2"');
    expect(files["playwright.config.ts"]).toContain('testDir: "./src/tests"');
    expect(files["src/tests/home.spec.ts"]).toContain("home.page");
    expect(files[".gitignore"]).toContain("node_modules");
  });

  test("scaffolds an advanced project with auth fixture and workflow", async () => {
    const baseDir = await createTempDir("scaffold-advanced-");
    tempDirs.push(baseDir);

    const result = await scaffoldProject(
      baseDir,
      createAdvancedPlaywrightConfig({
        projectName: "advanced-app",
        packageManager: "npm"
      }),
      { resolvedVersions }
    );

    const files = await readTextFiles(result.targetDir);
    const huskyPath = path.join(result.targetDir, ".husky/pre-commit");
    const huskyStat = await stat(huskyPath);

    expect(files["src/fixtures/test.fixture.ts"]).toContain("workerStorageState");
    expect(files["src/types/auth.ts"]).toContain("zod");
    expect(files[".github/workflows/playwright.yml"]).toContain("npx playwright test");
    expect(files["playwright.config.ts"]).toContain("allure-playwright");
    expect(files["playwright.config.ts"]).toContain("userAgent:");
    expect(files["README.md"]).toContain("- `HTML`\n- `Allure`");
    expect(huskyStat.mode & 0o111).not.toBe(0);
  });

  test("rejects scaffolding into a non-empty target directory", async () => {
    const baseDir = await createTempDir("scaffold-existing-");
    tempDirs.push(baseDir);

    await writeTextFile(baseDir, "my-qa-app/placeholder.txt", "occupied");

    await expect(scaffoldProject(baseDir, createPlaywrightConfig())).rejects.toThrow(
      'Target directory "my-qa-app" already exists and is not empty.'
    );
  });

  test("creates executable husky hook files", async () => {
    const baseDir = await createTempDir("scaffold-husky-");
    tempDirs.push(baseDir);

    const result = await scaffoldProject(baseDir, createPlaywrightConfig(), {
      resolvedVersions
    });

    await access(path.join(result.targetDir, ".husky/pre-commit"), constants.X_OK);
  });
});
