# {{projectName}}

Generated by `create-qa-app`.

## Stack

- Framework: {{frameworkLabel}}
- Architecture: {{architectureLabel}}
- Language: TypeScript
- Runtime validation: {{runtimeValidationLabel}}
- Reporting:
{{playwrightSelectedReportersList}}

## Getting Started

1. Install dependencies with `{{installCommand}}`.
2. Copy `.env.example` to `.env`.
3. Update `BASE_URL`, `USERNAME`, and `PASSWORD` for your target environment.
4. Run type checks with `{{typecheckCommand}}`.
5. Format the code with `{{formatCommand}}`.
6. Run lint checks with `{{lintCommand}}`.
7. Run your test suite.
8. Install Playwright browsers with `{{playwrightInstallBrowsersCommand}}`.

## Environment

- `.env` is loaded automatically via `dotenv` whenever the generated config reads environment values.
- `.env.example` is safe to commit and should document the variables your project expects.
- `.env` is ignored by git so secrets stay local.
- In CI, configure the same variables through your CI provider secrets instead of committing a real `.env` file.

## Quality Commands

- `{{formatCheckCommand}}` checks formatting.
- `{{lintFixCommand}}` auto-fixes lint issues where possible.

## Playwright Commands

- `{{playwrightRunTestsCommand}}` runs the end-to-end tests.
- `{{playwrightUiModeCommand}}` starts interactive UI mode.
- `{{playwrightProjectCommand}}` runs tests only on Desktop Chrome.
- `{{playwrightDebugCommand}}` runs tests in debug mode.
- `{{playwrightCodegenCommand}}` auto-generates tests with Codegen.

## Report Commands

{{playwrightReportCommandsList}}

## Architecture Notes

- Page Object Model (POM) keeps page abstractions separate from tests for long-term maintainability.
