# {{projectName}}

Generated by `create-qa-app`.

## Stack
- Framework: {{frameworkLabel}}
- Architecture: {{architectureLabel}}
- Language: TypeScript
- Runtime validation: {{runtimeValidationLabel}}
- Reporting:
{{playwrightSelectedReportersList}}

## Getting Started
1. Install dependencies with `{{installCommand}}`.
2. Run type checks with `{{typecheckCommand}}`.
3. Run your test suite.
4. Install Playwright browsers with `{{playwrightInstallBrowsersCommand}}`.

## Playwright Commands
- `{{playwrightRunTestsCommand}}` runs the end-to-end tests.
- `{{playwrightUiModeCommand}}` starts interactive UI mode.
- `{{playwrightProjectCommand}}` runs tests only on Desktop Chrome.
- `{{playwrightDebugCommand}}` runs tests in debug mode.
- `{{playwrightCodegenCommand}}` auto-generates tests with Codegen.

## Report Commands
{{playwrightReportCommandsList}}

## Architecture Notes
- `pom` keeps page abstractions separate from tests for long-term maintainability.
- `feature` keeps test assets grouped by business feature for easier ownership.
